#! /bin/sh
### BEGIN INIT INFO
# Provides:		  alarmserver
# Required-Start:	
# Required-Stop:	 
# Default-Start:	 2 3 4 5
# Default-Stop:	  0 1 6
# Short-Description: Alarm Server is a daemon providing a proxy to the Envisalink module
# Description:	   Alarm Server provides a daemon for interfacing the Envisalink module from other applications
### END INIT INFO

# Description: Alarm Server Init Script
# Author: Sean Schneyer <sean@linuxbox.org>

PATH=/bin:/usr/bin:/sbin:/usr/sbin
NAME=alarmserver.py
DAEMON_PATH=/opt/alarmserver
CONFIG=/opt/alarmserver/conf/alarmserver.cfg
PIDFILE=/var/run/$NAME.pid

# adding libs to library path
# No libs at this time?
# export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/alarmserver/libs

case "$1" in
  start)
	echo -n "Starting alarmserver: "
	start-stop-daemon --start  --pidfile $PIDFILE --make-pidfile  --background --no-close --chdir $DAEMON_PATH --exec $NAME > /dev/null 2>&1
	echo "done."
	;;
  stop)
	echo -n "Stopping alarmserver: "
	start-stop-daemon --stop --quiet --pidfile $PIDFILE
	rm $PIDFILE
	echo "done."
	;;
  restart)
	echo "Restarting alarmserver: "
	sh $0 stop
	sleep 10
	sh $0 start
	;;
  save)
	echo "Save is not implemented..."
	;;
  *)
	echo "Usage: /etc/init.d/alarmserver {start|stop|restart|save}"
	exit 1
	;;
esac
exit 0
